version: '3.8'

services:
  db:
    container_name: payments_db
    image: mysql:5.7
    restart: always
    env_file:
      - example
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  web:
    container_name: web_payments
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/payments
    ports:
      - '80:8000'
    env_file:
      - example
    depends_on:
      db:
        condition: service_healthy
